### ISSUE TITLE
Bot not reacting to reactions

### ISSUE THREAD

**Issue by abrahammurciano** [DenverCoder1/jct-discord-bot#141]
![image](https://user-images.githubusercontent.com/25041135/114094210-b6093200-98c4-11eb-81a2-6dd5de46294c.png)

**Comment by abrahammurciano** [comment]
```
2021-04-08 20:45:37.143495
Author:
JCT Bot#7590 (JCT Bot | [/])

Channel:
linear-algebra-2

Message:


Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/asyncio/tasks.py", line 489, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/utils/utils.py", line 149, in wait_for_reaction
    reaction, _ = await bot.wait_for(
  File "/app/.heroku/python/lib/python3.9/asyncio/tasks.py", line 491, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError


--------------------------
```

**Comment by abrahammurciano** [comment]
Seems to be a bug with discord.py Intents constructor causing it to not trigger on_reaction functions. Switching back to using setters fixed the issue
